version: '3.3'
services:
  mongodb:
    image: mongo:bionic
    restart: always
    volumes:
      - /usr/local/var/mongodb:/data/db
  
  api:
    build: ../api
    restart: always
    environment:
      - DatabaseSettings:ConnectionString=${DbConnectionString}
      - DatabaseSettings:DatabaseName=${DbName}
      - TwitchAppSettings:ClientId=${TwitchClientId}
      - TwitchAppSettings:ClientSecret=${TwitchClientSecret}
      - ASPNETCORE_ENVIRONMENT=Production

  portal:
    build: ../portal
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /usr/local/var/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot